[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.shell]
command = "shfmt"
includes = ["*.sh"]
options = ["-i", "2", "-s", "-w"]

[global]
excludes = [
  ".direnv",
  "secrets/*",
  ".conform.yaml",
  "treefmt.toml",
  ".editorconfig",
  ".github/settings.yml",
  "lefthook.yml",
  "book.toml"
]
