-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
local TERMINAL = nix.vars.terminal or "wezterm-gui"
local key = nix.vars.key or "SUPER"
local mod = nix.vars.mod or "SUPER"
local modifier = nix.vars.modifier or "alt"
local modifier_release = nix.vars.modifier_release or "ALT_L"
local reverse = nix.vars.reverse or "shift"
hl.curve("linear", {
    type = "bezier",
    points = {{0.0, 0.0}, {1.0, 1.0}}
})
hl.curve("md3_standard", {
    type = "bezier",
    points = {{0.2, 0}, {0, 1}}
})
hl.curve("md3_decel", {
    type = "bezier",
    points = {{0.05, 0.7}, {0.1, 1}}
})
hl.curve("md3_accel", {
    type = "bezier",
    points = {{0.3, 0}, {0.8, 0.15}}
})
hl.curve("overshot", {
    type = "bezier",
    points = {{0.05, 0.9}, {0.1, 1.1}}
})
hl.curve("crazyshot", {
    type = "bezier",
    points = {{0.1, 1.5}, {0.76, 0.92}}
})
hl.curve("hyprnostretch", {
    type = "bezier",
    points = {{0.05, 0.9}, {0.1, 1.1}}
})
hl.curve("menu_decel", {
    type = "bezier",
    points = {{0.1, 1}, {0, 1}}
})
hl.curve("menu_accel", {
    type = "bezier",
    points = {{0.38, 0.04}, {1, 0.07}}
})
hl.curve("easeOutBack", {
    type = "bezier",
    points = {{0.34, 1.3}, {0.64, 1}}
})
hl.curve("easeOutExpo", {
    type = "bezier",
    points = {{0.16, 1}, {0.3, 1}}
})
hl.curve("popIn", {
    type = "bezier",
    points = {{0.05, 0.9}, {0.1, 1.05}}
})
hl.curve("softAcDecel", {
    type = "bezier",
    points = {{0.26, 0.26}, {0.15, 1}}
})
hl.curve("md2", {
    type = "bezier",
    points = {{0.4, 0}, {0.2, 1}}
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 8,
    bezier = "md3_decel",
    style = "slide top"
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 8,
    bezier = "md3_standard",
    style = "slide top 0%"
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 8,
    bezier = "md3_standard",
    style = "slide top 0%"
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 8,
    bezier = "md3_standard",
    style = "slide top 20%"
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "menu_accel",
    style = "slide top 20%"
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 4,
    bezier = "menu_decel",
    style = "slide top 20%"
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 8,
    bezier = "default"
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 8,
    bezier = "default"
})
hl.animation({
    leaf = "fadeSwitch",
    enabled = true,
    speed = 8,
    bezier = "default"
})
hl.animation({
    leaf = "fadeShadow",
    enabled = true,
    speed = 8,
    bezier = "default"
})
hl.animation({
    leaf = "fadeDim",
    enabled = true,
    speed = 8,
    bezier = "default"
})
hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 8,
    bezier = "default"
})
hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 8,
    bezier = "default"
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 6,
    bezier = "linear"
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 100,
    bezier = "linear",
    style = "loop"
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 10,
    bezier = "default"
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 8,
    bezier = "default",
    style = "slidevert"
})

hl.bind(mod .. " + Return", hl.dsp.exec_cmd("waveterm"))
hl.bind("SUPER + ALT + Return", hl.dsp.exec_cmd("firefox"))
hl.bind("SUPER + SHIFT + K", hl.dsp.exec_cmd(nix.pkgs.keybindings))
hl.bind("SUPER + V", hl.dsp.exec_cmd("copyq toggle"))
hl.bind("SUPER + SHIFT + ESCAPE", hl.dsp.exec_cmd("dms ipc call powermenu toggle"))
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind(mod .. " + ESCAPE", hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.bind(mod .. " + G", hl.dsp.group.toggle())
hl.bind(mod .. " + SHIFT + N", hl.dsp.group.next())
hl.bind(mod .. " + SHIFT + P", hl.dsp.group.prev())
hl.bind(mod .. " + s", hl.dsp.layout("focus l"))
hl.bind(mod .. " + t", hl.dsp.layout("focus r"))
hl.bind(mod .. " + m", hl.dsp.layout("focus u"))
hl.bind(mod .. " + n", hl.dsp.layout("focus d"))
hl.bind(mod .. " + s", hl.dsp.layout("cyclenext"))
hl.bind(mod .. " + t", hl.dsp.layout("cycleprev"))
hl.bind(mod .. " + m", hl.dsp.layout("swapnext"))
hl.bind(mod .. " + n", hl.dsp.layout("swapprev"))
hl.bind(mod .. " + CTRL + s", hl.dsp.layout("move -col"))
hl.bind(mod .. " + CTRL + t", hl.dsp.layout("move +col"))
hl.bind(mod .. " + CTRL + m", hl.dsp.window.move({
    direction = "u"
}))
hl.bind(mod .. " + CTRL + n", hl.dsp.window.move({
    direction = "d"
}))
hl.bind("CTRL + ALT + t", hl.dsp.layout("colresize +conf"))
hl.bind("CTRL + ALT + s", hl.dsp.layout("colresize -conf"))
hl.bind(mod .. " + ALT + s", hl.dsp.window.move({
    direction = "left"
}))
hl.bind(mod .. " + ALT + t", hl.dsp.window.move({
    direction = "right"
}))
hl.bind(mod .. " + ALT + m", hl.dsp.window.move({
    direction = "up"
}))
hl.bind(mod .. " + ALT + n", hl.dsp.window.move({
    direction = "down"
}))
hl.bind("SUPER + SHIFT + s", hl.dsp.layout("swapcol l"))
hl.bind("SUPER + SHIFT + t", hl.dsp.layout("swapcol r"))
hl.bind("SUPER + SHIFT + m", hl.dsp.window.swap({
    direction = "u"
}))
hl.bind("SUPER + SHIFT + n", hl.dsp.window.swap({
    direction = "d"
}))
hl.bind("SUPER + bracketleft", hl.dsp.focus({
    workspace = -1
}))
hl.bind("SUPER + bracketright", hl.dsp.focus({
    workspace = "+1"
}))
hl.bind("SUPER + mouse_down", hl.dsp.focus({
    workspace = "e+1"
}))
hl.bind("SUPER + mouse_up", hl.dsp.focus({
    workspace = "e-1"
}))
hl.bind("XF86Launch1", hl.dsp.exec_cmd(nix.pkgs.yt))
hl.bind("Print", hl.dsp.exec_cmd(nix.pkgs.snapshot .. " area"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd(nix.pkgs.snapshot .. " active"))
hl.bind("ALT + Print", hl.dsp.exec_cmd(nix.pkgs.snapshot .. " output"))
hl.bind(mod .. " + SHIFT + y", hl.dsp.window.move({
    workspace = "special"
}))
hl.bind(mod .. " + y", hl.dsp.workspace.toggle_special("eDP-1"))
hl.bind(mod .. " + SHIFT + bracketleft", hl.dsp.focus({
    workspace = "m-1"
}))
hl.bind(mod .. " + SHIFT + bracketright", hl.dsp.focus({
    workspace = "m+1"
}))
hl.bind(mod .. " + CTRL + bracketleft", hl.dsp.focus({
    monitor = "l"
}))
hl.bind(mod .. " + CTRL + bracketright", hl.dsp.focus({
    monitor = "r"
}))
hl.bind(mod .. " + SHIFT + ALT + bracketleft", function()
    local w = hl.get_active_workspace();
    if not w then
        return
    end
    hl.dispatch(hl.dsp.workspace.move({
        workspace = w.id,
        monitor = "u"
    }))
end)
hl.bind(mod .. " + SHIFT + ALT + bracketright", function()
    local w = hl.get_active_workspace();
    if not w then
        return
    end
    hl.dispatch(hl.dsp.workspace.move({
        workspace = w.id,
        monitor = "d"
    }))
end)
hl.bind(mod .. " + M", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mod .. " + M", hl.dsp.window.move({
    workspace = "+0"
}))
hl.bind(mod .. " + M", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mod .. " + M", hl.dsp.window.move({
    workspace = "special:magic"
}))
hl.bind(mod .. " + M", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mod .. " + SHIFT + G", hl.dsp.exec_cmd("hyprland-profile-switcher --select \"walker -d\""))
hl.bind("CTRL + ALT + Delete", hl.dsp.exit())
hl.bind("SUPER + L", hl.dsp.exec_cmd("walker"))
hl.bind(mod .. " + X", hl.dsp.exec_cmd("noctalia-shell ipc call notifications toggleHistory"))
hl.bind(mod .. " + escape", hl.dsp.exec_cmd("noctalia-shell ipc call lockScreen lock"))
hl.bind(mod .. " + SHIFT + escape", hl.dsp.exec_cmd("noctalia-shell ipc call sessionMenu toggle"))
hl.bind(mod .. " + z", hl.dsp.workspace.toggle_special("term"))
hl.bind(mod .. " + j", hl.dsp.workspace.toggle_special("file"))
hl.bind(mod .. " + 1", hl.dsp.focus({
    workspace = 1
}))
hl.bind(mod .. " + SHIFT + 1", hl.dsp.window.move({
    workspace = 1
}))
hl.bind(mod .. " + 2", hl.dsp.focus({
    workspace = 2
}))
hl.bind(mod .. " + SHIFT + 2", hl.dsp.window.move({
    workspace = 2
}))
hl.bind(mod .. " + 3", hl.dsp.focus({
    workspace = 3
}))
hl.bind(mod .. " + SHIFT + 3", hl.dsp.window.move({
    workspace = 3
}))
hl.bind(mod .. " + 4", hl.dsp.focus({
    workspace = 4
}))
hl.bind(mod .. " + SHIFT + 4", hl.dsp.window.move({
    workspace = 4
}))
hl.bind(mod .. " + 5", hl.dsp.focus({
    workspace = 5
}))
hl.bind(mod .. " + SHIFT + 5", hl.dsp.window.move({
    workspace = 5
}))
hl.bind(mod .. " + 6", hl.dsp.focus({
    workspace = 6
}))
hl.bind(mod .. " + SHIFT + 6", hl.dsp.window.move({
    workspace = 6
}))
hl.bind(mod .. " + 7", hl.dsp.focus({
    workspace = 7
}))
hl.bind(mod .. " + SHIFT + 7", hl.dsp.window.move({
    workspace = 7
}))
hl.bind(mod .. " + 8", hl.dsp.focus({
    workspace = 8
}))
hl.bind(mod .. " + SHIFT + 8", hl.dsp.window.move({
    workspace = 8
}))
hl.bind(mod .. " + 9", hl.dsp.focus({
    workspace = 9
}))
hl.bind(mod .. " + SHIFT + 9", hl.dsp.window.move({
    workspace = 9
}))
hl.bind(mod .. " + 0", hl.dsp.focus({
    workspace = 10
}))
hl.bind(mod .. " + SHIFT + 0", hl.dsp.window.move({
    workspace = 10
}))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(nix.pkgpath.wireplumber .. "/bin/wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%+"), {
    locked = true,
    repeating = true
})
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(nix.pkgpath.wireplumber .. "/bin/wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%-"), {
    locked = true,
    repeating = true
})
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(nix.pkgs.brightnessctl .. " set +5%"), {
    locked = true,
    repeating = true
})
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(nix.pkgs.brightnessctl .. " set  5%-"), {
    locked = true,
    repeating = true
})

hl.bind("XF86AudioMute", hl.dsp.exec_cmd(nix.pkgpath.wireplumber .. "/bin/wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), {
    locked = true
})
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd(nix.pkgs.playerctl .. " play-pause"), {
    locked = true
})
hl.bind("XF86AudioStop", hl.dsp.exec_cmd(nix.pkgs.playerctl .. " pause"), {
    locked = true
})
hl.bind("XF86AudioPause", hl.dsp.exec_cmd(nix.pkgs.playerctl .. " pause"), {
    locked = true
})
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd(nix.pkgs.playerctl .. " previous"), {
    locked = true
})
hl.bind("XF86AudioNext", hl.dsp.exec_cmd(nix.pkgs.playerctl .. " next"), {
    locked = true
})

hl.bind("SUPER + mouse:272", hl.dsp.window.drag())

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "32")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "hyprqt6engine")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("OZONE_PLATFORM", "wayland")
hl.env("CHROMIUM_FLAGS", "\"--enable-features=UseOzonePlatform --ozone-platform=wayland --gtk-version=4\"")
hl.env("XDG_DATA_DIRS", "$XDG_DATA_DIRS:$HOME/.nix-profile/share:/nix/var/nix/profiles/default/share")
hl.env("XCOMPOSEFILE", "~/.XCompose")
hl.env("EDITOR", "nvim")
hl.env("GTK_THEME", "Adwaita:dark")

hl.layer_rule({
    match = {
        namespace = "match:namespace quickshell:bar"
    }
    -- TODO: manual review — unmapped layer rule: "blur on"
})

hl.layer_rule({
    match = {
        namespace = "match:namespace quickshell:popout"
    }
    -- TODO: manual review — unmapped layer rule: "blur on"
})

hl.layer_rule({
    match = {
        namespace = "match:namespace quickshell:modal"
    }
    -- TODO: manual review — unmapped layer rule: "blur on"
})

hl.layer_rule({
    match = {
        namespace = "no_screen_share on"
    }
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:bar"
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:popout"
    -- TODO: manual review — unmapped layer rule: "match:namespace quickshell:modal"
})

hl.layer_rule({
    match = {
        namespace = "no_anim on"
    }
    -- TODO: manual review — unmapped layer rule: "match:namespace selection"
})

hl.monitor({
    output = "DP-3",
    mode = "2560x1440@165",
    position = "0x0",
    scale = "1"
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60",
    position = "2560x0",
    scale = "1.5"
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1"
})

hl.window_rule({
    match = {
        class = "^(com.github.hluk.copyq)$"
    },
    float = true,
    stay_focused = true,
    center = true,
    size = "1800 1000"
})

hl.window_rule({
    match = {
        class = "^(system-monitoring-center)$"
    },
    float = true,
    center = true,
    size = "1800 1000"
})

hl.window_rule({
    match = {
        class = "([Tt]hunar)",
        title = "(File Operation Progress)"
    },
    float = true
})

hl.window_rule({
    match = {
        class = "([Tt]hunar)",
        title = "(Confirm to replace files)"
    },
    float = true
})

hl.window_rule({
    match = {
        class = "(codium|codium-url-handler|VSCodium|code-oss)",
        title = "(Add Folder to Workspace)"
    },
    float = true
})

hl.window_rule({
    match = {
        class = "(electron)",
        title = "(Add Folder to Workspace)"
    },
    float = true
})

hl.window_rule({
    match = {
        class = "^(nm-applet|nm-connection-editor|blueman-manager)$"
    },
    float = true
})

hl.window_rule({
    match = {
        class = "^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$"
    },
    float = true
})

hl.window_rule({
    match = {
        title = "(Kvantum Manager)"
    },
    float = true
})

hl.window_rule({
    match = {
        class = "^([Qq]alculate-gtk)$"
    },
    float = true
})

hl.window_rule({
    match = {
        title = "^(Picture-in-Picture)$"
    },
    float = true
})

hl.window_rule({
    match = {
        class = "^(.*jetbrains.*)$",
        title = "^(win[0-9]+)$"
    },
    no_initial_focus = true
})

hl.window_rule({
    match = {
        title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$"
    },
    tag = "+picture-in-picture"
})

hl.window_rule({
    match = {
        tag = "picture-in-picture"
    },
    float = true,
    keep_aspect_ratio = true,
    move = "73% 72%",
    size = "25% 25%",
    pin = true
})

hl.window_rule({
    match = {
        class = "^(Brave-browser(-beta|-dev)?)$"
    },
    opacity = "0.9 0.9"
})

hl.window_rule({
    match = {
        class = "^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr)$"
    },
    opacity = "0.9 0.9"
})

hl.window_rule({
    match = {
        class = "^(google-chrome(-beta|-dev|-unstable)?)$"
    },
    opacity = "0.9 0.9"
})

hl.window_rule({
    match = {
        class = "^(chrome-.+-Default)$"
    },
    opacity = "0.94 0.86"
})

hl.window_rule({
    match = {
        class = "^([Tt]hunar|org.gnome.Nautilus)$"
    },
    opacity = "0.9 0.8"
})

hl.window_rule({
    match = {
        class = "^(deluge)$"
    },
    opacity = "0.9 0.8"
})

hl.window_rule({
    match = {
        class = "^(org.wezfurlong.wezterm|Alacritty|kitty|kitty-dropterm)$"
    },
    opacity = "0.8 0.7"
})

hl.window_rule({
    match = {
        class = "^(VSCodium|codium-url-handler|code-oss)$"
    },
    opacity = "0.8 0.8"
})

hl.window_rule({
    match = {
        class = "^([Cc]ode)$"
    },
    opacity = "0.8 0.8"
})

hl.window_rule({
    match = {
        class = "^(nwg-look|qt5ct|qt6ct|[Yy]ad)$"
    },
    opacity = "0.9 0.8"
})

hl.window_rule({
    match = {
        class = "^(kvantummanager)"
    },
    opacity = "0.8 0.8"
})

hl.window_rule({
    match = {
        class = "^(com.obsproject.Studio)$"
    },
    opacity = "0.9 0.7"
})

hl.window_rule({
    match = {
        class = "^([Aa]udacious)$"
    },
    opacity = "0.9 0.7"
})

hl.window_rule({
    match = {
        class = "^(VSCode|code-url-handler)$"
    },
    opacity = "1 1"
})

hl.window_rule({
    match = {
        class = "^(jetbrains-.+)$"
    },
    opacity = "1 1"
})

hl.window_rule({
    match = {
        class = "^([Dd]iscord|[Vv]esktop)$"
    },
    opacity = "0.94 0.86"
})

hl.window_rule({
    match = {
        class = "^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$"
    },
    opacity = "0.9 0.8"
})

hl.window_rule({
    match = {
        class = "^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$"
    },
    opacity = "0.82 0.75"
})

hl.window_rule({
    match = {
        class = "^(xdg-desktop-portal-gtk)$"
    },
    opacity = "0.9 0.8"
})

hl.window_rule({
    match = {
        title = "^(Picture-in-Picture)$"
    },
    opacity = "0.95 0.75"
})

hl.workspace_rule({
    workspace = "special:term",
    -- ["on-created-empty"] = "wezterm-gui"
})

hl.workspace_rule({
    workspace = "special:file",
    -- ["on-created-empty"] = "dolphin"
})

hl.workspace_rule({
    workspace = "m[HDMI-A-1]",
    layout = "scrolling"
})

hl.workspace_rule({
    workspace = "m[DP-3]",
    layout = "master"
})

hl.config({
    decoration = {
        rounding = 10,
        dim_inactive = false,
        active_opacity = 0.95,
        blur = {
            enabled = true,
            size = 6,
            passes = 3,
            ignore_opacity = true,
            new_optimizations = true,
            xray = false,
            brightness = 1,
            noise = 0.01,
            contrast = 1,
            popups = true,
            popups_ignorealpha = 0.6
        },
        shadow = {
            offset = "0, 0",
            range = 30,
            render_power = 3,
            color = "0x66000000"
        }
    },
    ecosystem = {
        no_update_news = true
    },
    general = {
        gaps_in = 3,
        gaps_out = 8,
        border_size = 2,
        resize_on_border = true,
        col = {
            active_border = {
                colors = {nix.vars.lavender, nix.vars.mauve, nix.vars.red},
                angle = 45
            },
            inactive_border = "rgba(00000000)"
        }
    },
    group = {
        groupbar = {
            col = {
                active = "rgb(7fbbb3)",
                inactive = "rgb(859289)"
            },
            font_size = 10,
            text_color = nix.vars.textcolor
        },
        col = {
            border_active = {
                colors = {nix.vars.mauve, nix.vars.red, nix.vars.blue},
                angle = 45
            },
            border_inactive = {
                colors = {nix.vars.green, nix.vars.mauve},
                angle = 45
            },
            border_locked_active = {
                colors = {nix.vars.mauve, nix.vars.blue},
                angle = 45
            },
            border_locked_inactive = {
                colors = {nix.vars.green, nix.vars.mauve},
                angle = 45
            }
        }
    },
    misc = {
        background_color = "rgb(272e33)",
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
        vrr = 2
    },
    xwayland = {
        force_zero_scaling = true
    },
    debug = {
        disable_logs = false
    }
})

hl.on("hyprland.start", function()
    hl.exec_cmd(
        "dbus-update-activation-environment --systemd --all && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd(nix.pkgs.awww)
    hl.exec_cmd(nix.pkgpath.kwallet .. "/libexec/pam_kwallet_init")
    hl.exec_cmd("copyq --start-server")
    hl.exec_cmd("bash -c \"wl-paste --watch cliphist store &\"")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("noctalia-shell")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("hass-report-status http://homeassistant.local/api/webhook/eaea48a1-30e3-47bf-a076-30f816f0d3d1 true")
end)

