# { self, inputs, ... }:
{inputs, ...}: {
  flake-file.inputs = {
    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      # inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  imports = [inputs.treefmt-nix.flakeModule];

  perSystem =
    # { pkgs, ... }:
    # let
    #   treefmtEval = inputs'.treefmt-nix.lib.evalModule pkgs ./_treefmt.nix;
    # in
    {
      # Formatter for your nix files, available through 'nix fmt'
      # TODO: Uncomment when fixed.
      # formatter =
      #   # libx.forAllSystems (
      #   #   pkgs:
      #   #   inputs.nix-formatter-pack.lib.mkFormatter {
      #   #     config.tools = {
      #   #       alejandra.enable = false;
      #   #       deadnix.enable = false;
      #   #       nixpkgs.enable = true;
      #   #       nixpkgs-fmt.enable = false;
      #   #       statix.enable = false;
      #   #     };
      #   #   }
      #   # );
      # treefmtEval.config.build.wrapper;
      # checks = {
      # formatting = treefmtEval.config.build.check self;
      # };
      treefmt = {
        # Used to find the project root
        # projectRootFile = "flake.nix";
        projectRootFile = "flake.nix";
        enableDefaultExcludes = true;

        programs.alejandra = {
          # projectRootFile = "flake.nix";
          enable = true;
          includes = ["**/*.nix"];
          # excludes = [ ];
        };
        # settings.formatter.nixfmt.options = [ ];
        programs.deadnix.enable = true;
        programs.statix.enable = true;

        programs.shellcheck.enable = true;

        programs.ruff = {
          check = true;
          format = true;
        };
        settings.formatter.ruff-check.priority = 1;
        settings.formatter.ruff-format.priority = 2;

        programs.taplo.enable = true;

        programs.toml-sort.enable = true;

        programs.mdformat.enable = true;

        settings = {
          on-unmatched = "warn";
          global.excludes = [
            "**/.gitkeep"
            # ".leaderrc"
            # "*.el" # TODO contribute an emacs treefmt
            # "*/config/nvim/*"
            # "*/config/ghostty/*"
            # "*/config/wezterm/*"
            # "*/vic/dots/ssh/*"
            # "*/vic/secrets/*"
            "**/*.atrb"
            "**/*.key"
            "**/*.crt"
            "**/*.gitignore"
            "**/*.gitmodules"
            "**/.justfile" # TODO: Add support for formatting justfiles
            ".justfile"
            "**/LICENSE"
            "**/.direnv"
            "**/node_modules/*"
            "node_modules/*"
            "**/*.code-workspace"
            "*.code-workspace"
          ];

          # Enable the terraform formatter
          # programs.terraform.enable = true;
          # Override the default package
          # programs.terraform.package = pkgs.terraform_1;
          # Override the default settings generated by the above option
          # settings.formatter.terraform.excludes = [ "hello.tf" ];
        };
      };
    };
}
