# This file has been generated by node2nix 1.11.1. Do not edit!
{
  nodeEnv,
  fetchurl,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [ ],
  ...
}:
let
  sources = {
    "@taplo/core-0.2.0" = {
      name = "_at_taplo_slash_core";
      packageName = "@taplo/core";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@taplo/core/-/core-0.2.0.tgz";
        sha512 = "r8bl54Zj1In3QLkiW/ex694bVzpPJ9EhwqT9xkcUVODnVUGirdB1JTsmiIv0o1uwqZiwhi8xNnTOQBRQCpizrQ==";
      };
    };
    "@taplo/lib-0.5.0" = {
      name = "_at_taplo_slash_lib";
      packageName = "@taplo/lib";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@taplo/lib/-/lib-0.5.0.tgz";
        sha512 = "+xIqpQXJco3T+VGaTTwmhxLa51qpkQxCjRwezjFZgr+l21ExlywJFcDfTrNmL6lG6tqb0h8GyJKO3UPGPtSCWg==";
      };
    };
    "prettier-3.5.3" = {
      name = "prettier";
      packageName = "prettier";
      version = "3.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-3.5.3.tgz";
        sha512 = "QQtaxnoDJeAkDvDKWCLiwIXkTgRhwYDEQCghU9Z6q03iyek/rxRh/2lC3HB7P8sWT2xC/y5JDctPLBIGzHKbhw==";
      };
    };
  };
  args = {
    name = "prettier-plugin-toml";
    packageName = "prettier-plugin-toml";
    version = "2.0.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-toml/-/prettier-plugin-toml-2.0.5.tgz";
      sha256 = "sha256-DFJq5TVXqV2ahIDSnHbbKW8qbXqazxnpL4+yEVcLbUA=";
    };
    dependencies = [
      sources."@taplo/core-0.2.0"
      sources."@taplo/lib-0.5.0"
      sources."prettier-3.5.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An opinionated `toml` formatter plugin for Prettier";
      homepage = "https://github.com/un-ts/prettier/tree/master/packages/toml";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  inherit args;
  inherit sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (
    lib.overrideExisting args {
      src = stdenv.mkDerivation {
        name = args.name + "-package-json";
        src = nix-gitignore.gitignoreSourcePure [
          "*"
          "!package.json"
          "!package-lock.json"
        ] args.src;
        dontBuild = true;
        installPhase = "mkdir -p $out; cp -r ./* $out;";
      };
    }
  );
}
